<?php

declare(strict_types=1);

/*
 * This file is part of the slince/cycle-bundle package.
 *
 * (c) Slince <taosikai@yeah.net>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Slince\CycleBundle\Schema\SchemaDumper;

use Symfony\Component\VarExporter\VarExporter;

final class SymfonyVarExporterDumper extends Dumper
{
    /**
     * {@inheritdoc}
     */
    public function dump(array $options = []): string
    {
        return sprintf(<<<EOT
<?php

// This file has been auto-generated by the Cycle bundle.
// Generated on %s

use Cycle\ORM\Schema;

\$schema = %s;

return \$schema;
EOT
            ,
            (new \DateTime())->format(\DateTimeInterface::ATOM),
            VarExporter::export($this->getSchema())
        );
    }
}